
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 14 2024 23:05:22 IST (Nov 14 2024 17:35:22 UTC)

// Verification Directory fv/ETAI6 

module full_adder(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  ADDHX1 g31__2398(.A (B), .B (A), .CO (Cout), .S (Sum));
endmodule

module full_adder_5_1(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  ADDFX1 g85__5107(.A (A), .B (B), .CI (Cin), .CO (Cout), .S (Sum));
endmodule

module full_adder_5_2(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  ADDFX1 g85__6260(.A (A), .B (B), .CI (Cin), .CO (Cout), .S (Sum));
endmodule

module full_adder_5_3(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  ADDFX1 g85__4319(.A (A), .B (B), .CI (Cin), .CO (Cout), .S (Sum));
endmodule

module full_adder_5_4(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  ADDFX1 g85__8428(.A (A), .B (B), .CI (Cin), .CO (Cout), .S (Sum));
endmodule

module full_adder_5(A, B, Cin, Sum, Cout);
  input A, B, Cin;
  output Sum, Cout;
  wire A, B, Cin;
  wire Sum, Cout;
  ADDFX1 g85__5526(.A (A), .B (B), .CI (Cin), .CO (Cout), .S (Sum));
endmodule

module RCA_N6(X, Y, Ci, S, Co);
  input [5:0] X, Y;
  input Ci;
  output [5:0] S;
  output Co;
  wire [5:0] X, Y;
  wire Ci;
  wire [5:0] S;
  wire Co;
  wire [6:0] carry;
  wire UNCONNECTED_HIER_Z;
  full_adder \full_adder_chain[0].fa (.A (X[0]), .B (Y[0]), .Cin
       (UNCONNECTED_HIER_Z), .Sum (S[0]), .Cout (carry[1]));
  full_adder_5_1 \full_adder_chain[1].fa (.A (X[1]), .B (Y[1]), .Cin
       (carry[1]), .Sum (S[1]), .Cout (carry[2]));
  full_adder_5_2 \full_adder_chain[2].fa (.A (X[2]), .B (Y[2]), .Cin
       (carry[2]), .Sum (S[2]), .Cout (carry[3]));
  full_adder_5_3 \full_adder_chain[3].fa (.A (X[3]), .B (Y[3]), .Cin
       (carry[3]), .Sum (S[3]), .Cout (carry[4]));
  full_adder_5_4 \full_adder_chain[4].fa (.A (X[4]), .B (Y[4]), .Cin
       (carry[4]), .Sum (S[4]), .Cout (carry[5]));
  full_adder_5 \full_adder_chain[5].fa (.A (X[5]), .B (Y[5]), .Cin
       (carry[5]), .Sum (S[5]), .Cout (Co));
endmodule

module ETAI6(X, Y, S, Cout);
  input [15:0] X, Y;
  output [15:0] S;
  output Cout;
  wire [15:0] X, Y;
  wire [15:0] S;
  wire Cout;
  wire UNCONNECTED_HIER_Z0, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12;
  RCA_N6 precise_adder(.X (X[15:10]), .Y (Y[15:10]), .Ci
       (UNCONNECTED_HIER_Z0), .S (S[15:10]), .Co (Cout));
  OR4X1 g453__6783(.A (Y[1]), .B (X[1]), .C (n_9), .D (n_0), .Y (S[1]));
  NAND3BXL g454__3680(.AN (n_0), .B (n_5), .C (n_8), .Y (S[0]));
  OR3XL g455__1617(.A (Y[6]), .B (X[6]), .C (n_11), .Y (S[6]));
  OR3XL g456__2802(.A (Y[5]), .B (X[5]), .C (n_12), .Y (S[5]));
  OR4X1 g458__1705(.A (Y[3]), .B (X[3]), .C (n_7), .D (n_12), .Y
       (S[3]));
  OR4X1 g459__5122(.A (Y[2]), .B (X[2]), .C (n_9), .D (n_12), .Y
       (S[2]));
  OR4X1 g460__8246(.A (X[4]), .B (Y[4]), .C (n_4), .D (n_12), .Y
       (S[4]));
  OR3XL g461__7098(.A (Y[7]), .B (X[7]), .C (n_6), .Y (S[7]));
  OAI2BB1X1 g463__6131(.A0N (Y[6]), .A1N (X[6]), .B0 (n_10), .Y (n_12));
  INVXL g464(.A (n_10), .Y (n_11));
  AOI21XL g465__1881(.A0 (Y[7]), .A1 (X[7]), .B0 (n_6), .Y (n_10));
  INVXL g466(.A (n_8), .Y (n_9));
  OR3XL g467__5115(.A (X[8]), .B (Y[8]), .C (n_2), .Y (S[8]));
  AOI21XL g468__7482(.A0 (Y[3]), .A1 (X[3]), .B0 (n_7), .Y (n_8));
  OAI2BB1X1 g469__4733(.A0N (Y[4]), .A1N (X[4]), .B0 (n_3), .Y (n_7));
  AOI211XL g470__6161(.A0 (Y[1]), .A1 (X[1]), .B0 (Y[0]), .C0 (X[0]),
       .Y (n_5));
  OAI2BB1X1 g471__9315(.A0N (Y[8]), .A1N (X[8]), .B0 (n_1), .Y (n_6));
  OR2XL g472__9945(.A (Y[9]), .B (X[9]), .Y (S[9]));
  INVXL g473(.A (n_3), .Y (n_4));
  INVXL g474(.A (n_1), .Y (n_2));
  NAND2XL g475__2883(.A (Y[5]), .B (X[5]), .Y (n_3));
  NAND2XL g476__2346(.A (Y[9]), .B (X[9]), .Y (n_1));
  AO21XL g2__1666(.A0 (Y[2]), .A1 (X[2]), .B0 (n_12), .Y (n_0));
endmodule

