
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 14 2024 11:12:10 IST (Nov 14 2024 05:42:10 UTC)

// Verification Directory fv/HERLOA 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_22(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_21(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_20(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_19(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_18(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5526(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_17(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6783(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_16(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__3680(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_15(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__1617(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_14(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2802(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_13(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__1705(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_12(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  wire n_0;
  XNOR2X1 g37__5122(.A (n_0), .B (Ci), .Y (S));
  XNOR2X1 g38__8246(.A (Y), .B (X), .Y (n_0));
endmodule

module RCA_N12(X, Y, Ci, S, Co);
  input [11:0] X, Y;
  input Ci;
  output [11:0] S;
  output Co;
  wire [11:0] X, Y;
  wire Ci;
  wire [11:0] S;
  wire Co;
  wire [10:0] w;
  wire n_0;
  fulladder \adder_stage[0].genblk1.FA (X[0], Y[0], Ci, S[0], w[0]);
  fulladder_22 \adder_stage[1].genblk1.FA (X[1], Y[1], w[0], S[1],
       w[1]);
  fulladder_21 \adder_stage[2].genblk1.FA (X[2], Y[2], w[1], S[2],
       w[2]);
  fulladder_20 \adder_stage[3].genblk1.FA (X[3], Y[3], w[2], S[3],
       w[3]);
  fulladder_19 \adder_stage[4].genblk1.FA (X[4], Y[4], w[3], S[4],
       w[4]);
  fulladder_18 \adder_stage[5].genblk1.FA (X[5], Y[5], w[4], S[5],
       w[5]);
  fulladder_17 \adder_stage[6].genblk1.FA (X[6], Y[6], w[5], S[6],
       w[6]);
  fulladder_16 \adder_stage[7].genblk1.FA (X[7], Y[7], w[6], S[7],
       w[7]);
  fulladder_15 \adder_stage[8].genblk1.FA (X[8], Y[8], w[7], S[8],
       w[8]);
  fulladder_14 \adder_stage[9].genblk1.FA (X[9], Y[9], w[8], S[9],
       w[9]);
  fulladder_13 \adder_stage[10].genblk1.FA (X[10], Y[10], w[9], S[10],
       w[10]);
  fulladder_12 \adder_stage[11].genblk1.FA (X[11], Y[11], w[10], S[11],
       n_0);
endmodule

module HERLOA(A, B, S);
  input [15:0] A, B;
  output [15:0] S;
  wire [15:0] A, B;
  wire [15:0] S;
  wire Cin, cout, n_0, n_1, n_2;
  RCA_N12 RCA1(.X (A[15:4]), .Y (B[15:4]), .Ci (Cin), .S (S[15:4]), .Co
       (cout));
  OR3XL g131__7098(.A (B[1]), .B (A[1]), .C (n_2), .Y (S[1]));
  OR3XL g132__6131(.A (B[0]), .B (A[0]), .C (n_2), .Y (S[0]));
  OA22X1 g133__1881(.A0 (n_0), .A1 (n_1), .B0 (B[2]), .B1 (A[2]), .Y
       (S[2]));
  NAND2BXL g134__5115(.AN (n_1), .B (n_0), .Y (S[3]));
  NOR2BX1 g135__7482(.AN (n_1), .B (n_0), .Y (n_2));
  ADDHX1 g136__4733(.A (B[3]), .B (A[3]), .CO (Cin), .S (n_1));
  NAND2XL g137__6161(.A (B[2]), .B (A[2]), .Y (n_0));
endmodule

