
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 17 2024 11:35:29 IST (Nov 17 2024 06:05:29 UTC)

// Verification Directory fv/OLOCAk8 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_14(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_13(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_12(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_11(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_10(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5526(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_9(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6783(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_8(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__3680(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module ripple_adder(X, Y, cin, S, Co);
  input [7:0] X, Y;
  input cin;
  output [7:0] S;
  output Co;
  wire [7:0] X, Y;
  wire cin;
  wire [7:0] S;
  wire Co;
  wire w1, w2, w3, w4, w5, w6, w7;
  fulladder u1(X[0], Y[0], cin, S[0], w1);
  fulladder_14 u2(X[1], Y[1], w1, S[1], w2);
  fulladder_13 u3(X[2], Y[2], w2, S[2], w3);
  fulladder_12 u4(X[3], Y[3], w3, S[3], w4);
  fulladder_11 u5(X[4], Y[4], w4, S[4], w5);
  fulladder_10 u6(X[5], Y[5], w5, S[5], w6);
  fulladder_9 u7(X[6], Y[6], w6, S[6], w7);
  fulladder_8 u8(X[7], Y[7], w7, S[7], Co);
endmodule

module OLOCAk8(a, b, sum, carry);
  input [15:0] a, b;
  output [15:0] sum;
  output carry;
  wire [15:0] a, b;
  wire [15:0] sum;
  wire carry;
  wire wire_carry;
  assign sum[0] = 1'b1;
  assign sum[1] = 1'b1;
  assign sum[2] = 1'b1;
  assign sum[3] = 1'b1;
  assign sum[4] = 1'b1;
  assign sum[5] = 1'b1;
  ripple_adder ra(a[15:8], b[15:8], wire_carry, sum[15:8], carry);
  OR2XL g10__1617(.A (b[7]), .B (a[7]), .Y (sum[7]));
  AND2X1 g11__2802(.A (a[7]), .B (b[7]), .Y (wire_carry));
  OR2XL g4__1705(.A (b[6]), .B (a[6]), .Y (sum[6]));
endmodule

