
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 14 2024 11:07:55 IST (Nov 14 2024 05:37:55 UTC)

// Verification Directory fv/HERLOA 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_20(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_19(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_18(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_17(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_16(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5526(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_15(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6783(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_14(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__3680(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_13(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__1617(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_12(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2802(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_11(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  wire n_0;
  XNOR2X1 g37__1705(.A (n_0), .B (Ci), .Y (S));
  XNOR2X1 g38__5122(.A (Y), .B (X), .Y (n_0));
endmodule

module RCA_N11(X, Y, Ci, S, Co);
  input [10:0] X, Y;
  input Ci;
  output [10:0] S;
  output Co;
  wire [10:0] X, Y;
  wire Ci;
  wire [10:0] S;
  wire Co;
  wire [9:0] w;
  wire n_0;
  fulladder \adder_stage[0].genblk1.FA (X[0], Y[0], Ci, S[0], w[0]);
  fulladder_20 \adder_stage[1].genblk1.FA (X[1], Y[1], w[0], S[1],
       w[1]);
  fulladder_19 \adder_stage[2].genblk1.FA (X[2], Y[2], w[1], S[2],
       w[2]);
  fulladder_18 \adder_stage[3].genblk1.FA (X[3], Y[3], w[2], S[3],
       w[3]);
  fulladder_17 \adder_stage[4].genblk1.FA (X[4], Y[4], w[3], S[4],
       w[4]);
  fulladder_16 \adder_stage[5].genblk1.FA (X[5], Y[5], w[4], S[5],
       w[5]);
  fulladder_15 \adder_stage[6].genblk1.FA (X[6], Y[6], w[5], S[6],
       w[6]);
  fulladder_14 \adder_stage[7].genblk1.FA (X[7], Y[7], w[6], S[7],
       w[7]);
  fulladder_13 \adder_stage[8].genblk1.FA (X[8], Y[8], w[7], S[8],
       w[8]);
  fulladder_12 \adder_stage[9].genblk1.FA (X[9], Y[9], w[8], S[9],
       w[9]);
  fulladder_11 \adder_stage[10].genblk1.FA (X[10], Y[10], w[9], S[10],
       n_0);
endmodule

module HERLOA(A, B, S);
  input [15:0] A, B;
  output [15:0] S;
  wire [15:0] A, B;
  wire [15:0] S;
  wire Cin, cout, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6;
  RCA_N11 RCA1(.X (A[15:5]), .Y (B[15:5]), .Ci (Cin), .S (S[15:5]), .Co
       (cout));
  NAND2XL g183__8246(.A (n_3), .B (n_6), .Y (S[2]));
  NAND2XL g184__7098(.A (n_2), .B (n_6), .Y (S[1]));
  NAND2XL g185__6131(.A (n_0), .B (n_6), .Y (S[0]));
  OAI2BB1X1 g186__1881(.A0N (A[3]), .A1N (n_5), .B0 (n_4), .Y (S[3]));
  NAND2XL g187__5115(.A (n_1), .B (n_5), .Y (n_6));
  OR2XL g188__7482(.A (n_1), .B (n_5), .Y (S[4]));
  ADDHX1 g189__4733(.A (B[4]), .B (A[4]), .CO (Cin), .S (n_5));
  XNOR2X1 g190__6161(.A (B[3]), .B (A[3]), .Y (n_4));
  NOR2XL g191__9315(.A (B[2]), .B (A[2]), .Y (n_3));
  NOR2XL g192__9945(.A (B[1]), .B (A[1]), .Y (n_2));
  NOR2XL g193__2883(.A (B[0]), .B (A[0]), .Y (n_0));
  AND2X1 g194__2346(.A (A[3]), .B (B[3]), .Y (n_1));
endmodule

