
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 16 2024 13:48:59 IST (Nov 16 2024 08:18:59 UTC)

// Verification Directory fv/ECPETA 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_18(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_17(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_16(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_15(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_14(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5526(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_13(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6783(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_12(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__3680(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_11(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__1617(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_10(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  wire n_0;
  XNOR2X1 g37__2802(.A (n_0), .B (Ci), .Y (S));
  XNOR2X1 g38__1705(.A (Y), .B (X), .Y (n_0));
endmodule

module RCA(X, Y, Ci, S, Co);
  input [9:0] X, Y;
  input Ci;
  output [9:0] S;
  output Co;
  wire [9:0] X, Y;
  wire Ci;
  wire [9:0] S;
  wire Co;
  wire [8:0] w;
  wire n_0;
  fulladder \adder_stage[0].genblk1.FA (X[0], Y[0], Ci, S[0], w[0]);
  fulladder_18 \adder_stage[1].genblk1.FA (X[1], Y[1], w[0], S[1],
       w[1]);
  fulladder_17 \adder_stage[2].genblk1.FA (X[2], Y[2], w[1], S[2],
       w[2]);
  fulladder_16 \adder_stage[3].genblk1.FA (X[3], Y[3], w[2], S[3],
       w[3]);
  fulladder_15 \adder_stage[4].genblk1.FA (X[4], Y[4], w[3], S[4],
       w[4]);
  fulladder_14 \adder_stage[5].genblk1.FA (X[5], Y[5], w[4], S[5],
       w[5]);
  fulladder_13 \adder_stage[6].genblk1.FA (X[6], Y[6], w[5], S[6],
       w[6]);
  fulladder_12 \adder_stage[7].genblk1.FA (X[7], Y[7], w[6], S[7],
       w[7]);
  fulladder_11 \adder_stage[8].genblk1.FA (X[8], Y[8], w[7], S[8],
       w[8]);
  fulladder_10 \adder_stage[9].genblk1.FA (X[9], Y[9], w[8], S[9], n_0);
endmodule

module ECPETA(A, B, sum);
  input [15:0] A, B;
  output [15:0] sum;
  wire [15:0] A, B;
  wire [15:0] sum;
  wire Cin, cout, n_0, n_1, n_2, n_3, n_4;
  RCA RCA1(A[15:6], B[15:6], Cin, sum[15:6], cout);
  OR3XL g238__5122(.A (B[1]), .B (A[1]), .C (n_0), .Y (sum[1]));
  OR4X1 g239__8246(.A (B[0]), .B (A[0]), .C (n_1), .D (n_0), .Y
       (sum[0]));
  AOI2BB1XL g240__7098(.A0N (B[5]), .A1N (A[5]), .B0 (Cin), .Y
       (sum[5]));
  OR3XL g241__6131(.A (B[2]), .B (A[2]), .C (n_4), .Y (sum[2]));
  NAND2XL g243__1881(.A (n_3), .B (n_2), .Y (sum[3]));
  OAI2BB1X1 g245__5115(.A0N (B[3]), .A1N (A[3]), .B0 (n_2), .Y (n_4));
  OAI2BB1X1 g246__7482(.A0N (B[5]), .A1N (A[5]), .B0 (n_2), .Y (Cin));
  OR2XL g247__4733(.A (B[4]), .B (A[4]), .Y (sum[4]));
  NOR2XL g248__6161(.A (B[3]), .B (A[3]), .Y (n_3));
  AND2X1 g249__9315(.A (A[1]), .B (B[1]), .Y (n_1));
  NAND2XL g250__9945(.A (B[4]), .B (A[4]), .Y (n_2));
  AO21XL g2__2883(.A0 (B[2]), .A1 (A[2]), .B0 (n_4), .Y (n_0));
endmodule

