
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 14 2024 11:01:28 IST (Nov 14 2024 05:31:28 UTC)

// Verification Directory fv/HERLOA 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_16(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_15(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_14(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_13(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_12(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5526(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_11(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6783(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_10(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__3680(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_9(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  wire n_0;
  XNOR2X1 g37__1617(.A (n_0), .B (Ci), .Y (S));
  XNOR2X1 g38__2802(.A (Y), .B (X), .Y (n_0));
endmodule

module RCA_N9(X, Y, Ci, S, Co);
  input [8:0] X, Y;
  input Ci;
  output [8:0] S;
  output Co;
  wire [8:0] X, Y;
  wire Ci;
  wire [8:0] S;
  wire Co;
  wire [7:0] w;
  wire n_0;
  fulladder \adder_stage[0].genblk1.FA (X[0], Y[0], Ci, S[0], w[0]);
  fulladder_16 \adder_stage[1].genblk1.FA (X[1], Y[1], w[0], S[1],
       w[1]);
  fulladder_15 \adder_stage[2].genblk1.FA (X[2], Y[2], w[1], S[2],
       w[2]);
  fulladder_14 \adder_stage[3].genblk1.FA (X[3], Y[3], w[2], S[3],
       w[3]);
  fulladder_13 \adder_stage[4].genblk1.FA (X[4], Y[4], w[3], S[4],
       w[4]);
  fulladder_12 \adder_stage[5].genblk1.FA (X[5], Y[5], w[4], S[5],
       w[5]);
  fulladder_11 \adder_stage[6].genblk1.FA (X[6], Y[6], w[5], S[6],
       w[6]);
  fulladder_10 \adder_stage[7].genblk1.FA (X[7], Y[7], w[6], S[7],
       w[7]);
  fulladder_9 \adder_stage[8].genblk1.FA (X[8], Y[8], w[7], S[8], n_0);
endmodule

module HERLOA(A, B, S);
  input [15:0] A, B;
  output [15:0] S;
  wire [15:0] A, B;
  wire [15:0] S;
  wire Cin, cout, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8;
  RCA_N9 RCA1(.X (A[15:7]), .Y (B[15:7]), .Ci (Cin), .S (S[15:7]), .Co
       (cout));
  NAND2XL g181__1705(.A (n_5), .B (n_8), .Y (S[4]));
  NAND2XL g182__5122(.A (n_3), .B (n_8), .Y (S[3]));
  NAND2XL g183__8246(.A (n_4), .B (n_8), .Y (S[0]));
  NAND2XL g184__7098(.A (n_1), .B (n_8), .Y (S[2]));
  NAND2XL g185__6131(.A (n_0), .B (n_8), .Y (S[1]));
  OAI2BB1X1 g186__1881(.A0N (A[5]), .A1N (n_7), .B0 (n_6), .Y (S[5]));
  NAND2XL g187__5115(.A (n_2), .B (n_7), .Y (n_8));
  OR2XL g188__7482(.A (n_2), .B (n_7), .Y (S[6]));
  ADDHX1 g189__4733(.A (B[6]), .B (A[6]), .CO (Cin), .S (n_7));
  XNOR2X1 g190__6161(.A (B[5]), .B (A[5]), .Y (n_6));
  NOR2XL g191__9315(.A (B[4]), .B (A[4]), .Y (n_5));
  NOR2XL g192__9945(.A (B[0]), .B (A[0]), .Y (n_4));
  NOR2XL g193__2883(.A (B[3]), .B (A[3]), .Y (n_3));
  NOR2XL g194__2346(.A (B[2]), .B (A[2]), .Y (n_1));
  NOR2XL g195__1666(.A (B[1]), .B (A[1]), .Y (n_0));
  AND2X1 g196__7410(.A (A[5]), .B (B[5]), .Y (n_2));
endmodule

