
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 16 2024 13:35:54 IST (Nov 16 2024 08:05:54 UTC)

// Verification Directory fv/ECPETA 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_10(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_9(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_8(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_7(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_6(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  wire n_0;
  XNOR2X1 g37__5526(.A (n_0), .B (Ci), .Y (S));
  XNOR2X1 g38__6783(.A (Y), .B (X), .Y (n_0));
endmodule

module RCA(X, Y, Ci, S, Co);
  input [5:0] X, Y;
  input Ci;
  output [5:0] S;
  output Co;
  wire [5:0] X, Y;
  wire Ci;
  wire [5:0] S;
  wire Co;
  wire [4:0] w;
  wire n_0;
  fulladder \adder_stage[0].genblk1.FA (X[0], Y[0], Ci, S[0], w[0]);
  fulladder_10 \adder_stage[1].genblk1.FA (X[1], Y[1], w[0], S[1],
       w[1]);
  fulladder_9 \adder_stage[2].genblk1.FA (X[2], Y[2], w[1], S[2], w[2]);
  fulladder_8 \adder_stage[3].genblk1.FA (X[3], Y[3], w[2], S[3], w[3]);
  fulladder_7 \adder_stage[4].genblk1.FA (X[4], Y[4], w[3], S[4], w[4]);
  fulladder_6 \adder_stage[5].genblk1.FA (X[5], Y[5], w[4], S[5], n_0);
endmodule

module ECPETA(A, B, sum);
  input [15:0] A, B;
  output [15:0] sum;
  wire [15:0] A, B;
  wire [15:0] sum;
  wire Cin, cout, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10;
  RCA RCA1(A[15:10], B[15:10], Cin, sum[15:10], cout);
  OR3XL g449__3680(.A (B[1]), .B (A[1]), .C (n_10), .Y (sum[1]));
  OR4X1 g450__1617(.A (B[0]), .B (A[0]), .C (n_2), .D (n_10), .Y
       (sum[0]));
  OR3XL g451__2802(.A (B[3]), .B (A[3]), .C (n_7), .Y (sum[3]));
  OR3XL g452__1705(.A (B[2]), .B (A[2]), .C (n_9), .Y (sum[2]));
  OAI2BB1X1 g453__5122(.A0N (B[2]), .A1N (A[2]), .B0 (n_8), .Y (n_10));
  INVXL g454(.A (n_8), .Y (n_9));
  AOI21XL g455__8246(.A0 (B[3]), .A1 (A[3]), .B0 (n_7), .Y (n_8));
  OR3XL g456__7098(.A (B[5]), .B (A[5]), .C (n_0), .Y (sum[5]));
  OR3XL g457__6131(.A (B[4]), .B (A[4]), .C (n_6), .Y (sum[4]));
  OAI2BB1X1 g458__1881(.A0N (B[4]), .A1N (A[4]), .B0 (n_5), .Y (n_7));
  INVXL g459(.A (n_5), .Y (n_6));
  AOI21XL g460__5115(.A0 (B[5]), .A1 (A[5]), .B0 (n_0), .Y (n_5));
  AOI2BB1XL g461__7482(.A0N (B[9]), .A1N (A[9]), .B0 (Cin), .Y
       (sum[9]));
  OR3XL g462__4733(.A (B[6]), .B (A[6]), .C (n_4), .Y (sum[6]));
  NAND2XL g464__6161(.A (n_1), .B (n_3), .Y (sum[7]));
  OAI2BB1X1 g466__9315(.A0N (B[7]), .A1N (A[7]), .B0 (n_3), .Y (n_4));
  OAI2BB1X1 g467__9945(.A0N (B[9]), .A1N (A[9]), .B0 (n_3), .Y (Cin));
  OR2XL g468__2883(.A (B[8]), .B (A[8]), .Y (sum[8]));
  NAND2XL g469__2346(.A (B[8]), .B (A[8]), .Y (n_3));
  AND2X1 g470__1666(.A (A[1]), .B (B[1]), .Y (n_2));
  NOR2XL g471__7410(.A (B[7]), .B (A[7]), .Y (n_1));
  AO21XL g2__6417(.A0 (B[6]), .A1 (A[6]), .B0 (n_4), .Y (n_0));
endmodule

