
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 13 2024 19:06:46 IST (Nov 13 2024 13:36:46 UTC)

// Verification Directory fv/CPETA 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_10(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_9(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_8(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_7(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_6(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  wire n_0;
  XNOR2X1 g37__5526(.A (n_0), .B (Ci), .Y (S));
  XNOR2X1 g38__6783(.A (Y), .B (X), .Y (n_0));
endmodule

module RCA(X, Y, Ci, S, Co);
  input [5:0] X, Y;
  input Ci;
  output [5:0] S;
  output Co;
  wire [5:0] X, Y;
  wire Ci;
  wire [5:0] S;
  wire Co;
  wire [4:0] w;
  wire n_0;
  fulladder \adder_stage[0].genblk1.FA (X[0], Y[0], Ci, S[0], w[0]);
  fulladder_10 \adder_stage[1].genblk1.FA (X[1], Y[1], w[0], S[1],
       w[1]);
  fulladder_9 \adder_stage[2].genblk1.FA (X[2], Y[2], w[1], S[2], w[2]);
  fulladder_8 \adder_stage[3].genblk1.FA (X[3], Y[3], w[2], S[3], w[3]);
  fulladder_7 \adder_stage[4].genblk1.FA (X[4], Y[4], w[3], S[4], w[4]);
  fulladder_6 \adder_stage[5].genblk1.FA (X[5], Y[5], w[4], S[5], n_0);
endmodule

module CPETA(A, B, sum);
  input [15:0] A, B;
  output [15:0] sum;
  wire [15:0] A, B;
  wire [15:0] sum;
  wire Cin, cout, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11;
  RCA RCA1(A[15:10], B[15:10], Cin, sum[15:10], cout);
  NAND2XL g339__3680(.A (n_3), .B (n_11), .Y (sum[0]));
  NAND2XL g340__1617(.A (n_0), .B (n_11), .Y (sum[1]));
  OR3XL g341__2802(.A (B[2]), .B (A[2]), .C (n_10), .Y (sum[2]));
  OR3XL g342__1705(.A (B[3]), .B (A[3]), .C (n_9), .Y (sum[3]));
  AOI21XL g343__5122(.A0 (B[2]), .A1 (A[2]), .B0 (n_10), .Y (n_11));
  OAI2BB1X1 g344__8246(.A0N (B[3]), .A1N (A[3]), .B0 (n_8), .Y (n_10));
  OR3XL g345__7098(.A (B[4]), .B (A[4]), .C (n_7), .Y (sum[4]));
  INVXL g346(.A (n_8), .Y (n_9));
  OR3XL g347__6131(.A (B[5]), .B (A[5]), .C (n_6), .Y (sum[5]));
  AOI21XL g348__1881(.A0 (B[4]), .A1 (A[4]), .B0 (n_7), .Y (n_8));
  OAI2BB1X1 g349__5115(.A0N (B[5]), .A1N (A[5]), .B0 (n_5), .Y (n_7));
  OR3XL g350__7482(.A (B[6]), .B (A[6]), .C (n_4), .Y (sum[6]));
  INVXL g351(.A (n_5), .Y (n_6));
  OR3XL g352__4733(.A (A[7]), .B (B[7]), .C (n_2), .Y (sum[7]));
  AOI21XL g353__6161(.A0 (B[6]), .A1 (A[6]), .B0 (n_4), .Y (n_5));
  OAI2BB1X1 g354__9315(.A0N (B[7]), .A1N (A[7]), .B0 (n_1), .Y (n_4));
  AOI211XL g355__9945(.A0 (B[1]), .A1 (A[1]), .B0 (B[0]), .C0 (A[0]),
       .Y (n_3));
  OR2XL g356__2883(.A (B[8]), .B (A[8]), .Y (sum[8]));
  INVXL g357(.A (n_1), .Y (n_2));
  NOR2XL g358__2346(.A (B[1]), .B (A[1]), .Y (n_0));
  NAND2XL g359__1666(.A (B[8]), .B (A[8]), .Y (n_1));
  ADDHX1 g166__7410(.A (B[9]), .B (A[9]), .CO (Cin), .S (sum[9]));
endmodule

